# Generated by Django 5.2.8 on 2025-11-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TombolaDisplay', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='id',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
