# Generated by Django 5.2.8 on 2025-11-20 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TombolaDisplay', '0002_remove_ticket_id_alter_ticket_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='identifier',
        ),
        migrations.AddField(
            model_name='participant',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=2.0),
        ),
    ]
