# Generated by Django 5.2.8 on 2025-11-20 13:34

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TombolaDisplay', '0003_remove_participant_identifier_participant_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tombola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TombolaDisplay.tombola'),
        ),
        migrations.AddField(
            model_name='tombola',
            name='finished_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tombola',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
