# Generated by Django 5.2.8 on 2025-11-20 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TombolaDisplay', '0004_ticket_is_available_ticket_tombola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tombola',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TombolaDisplay.participant'),
        ),
    ]
